### ISSUE TITLE
Errors bringing up inpainter to use against the Replicate API

### ISSUE THREAD

**Issue by kingdonb** [replicate/inpainter#31]
Error related to `*.replicate.delivery` image host pattern - the images are not returned to the user from the API, when a simple following of the instructions is undertaken. Upgrading to the next minor release of `next` solves it.

I also noticed an error in the log output that mentions an unknown property `clasName` - I'll submit a PR to fix all these!

**Comment by kingdonb** [comment]
https://stackoverflow.com/questions/71235874/how-to-allow-all-domains-for-image-nextjs-config#comment131396672_73951135

According to the above - the `remotePatterns` feature merged to use in 1cc5f0757a914c4f859ce6206abfd7293adf4b5f was only experimental in next 12.2

The error is:

```
  - The value at .images has an unexpected property, remotePatterns, which is not in the list of allowed properties (contentSecurityPolicy, dangerouslyAllowSVG, deviceSizes, disableStaticImages, domains, formats, imageSizes, loader, minimumCacheTTL, path).
```

The error in the UI occurs when the API call returns, (you get a big ugly red error stating that the image delivery host is not valid.)

**Comment by kingdonb** [comment]
I'm able to use the Replicate API and demonstrate its use through this example, having read zero pages of the manual - bravo!

**Comment by zeke** [comment]
> I'm able to use the Replicate API and demonstrate its use through this example

Thanks, @kingdonb ✨ That's what we made it for!

Thanks also for your pull request https://github.com/replicate/inpainter/pull/32 -- I've merged and deployed it. 🙏🏼
